API_TOKEN = '7102857857:AAFI41QmDKb1Wd2-DzX9uLlxqoj0353UeWY'
OPENAI_API_KEY = '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'

DB_USER = 'admin'
DB_PASSWORD = 'admin'
DB_HOST = 'localhost'
DB_NAME = 'postgres'

REFERRAL_BONUS = 5
DAILY_LIMIT = 30
