from .profile import register_handlers_profile
from .subscription import register_handlers_subscription
from .referral import register_handlers_referral
from .settings import register_handlers_settings
from .chat import register_handlers_chat
from .payment import register_handlers_payment